### ISSUE TITLE
horizontal-split causes line-wrapping

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/DFeed#56]
see e.g. https://dl.dropboxusercontent.com/u/910836/Screen%20Shot%202016-01-25%20at%2012.50.38.png

Toggling off the navigation avoids this, but one shouldn't have to do that.

**Comment by CyberShadow** [comment]
Unfortunately, Rory is using Gmail, who refuse to implement RFC 2646/3646 (format=flowed). Although DFeed implements some heuristics to reflow such messages, they fail in this case because Rory is using line breaks as both line separators and paragraph separators.

Ultimately, this is not fixable (without getting Gmail to implement format=flowed). There will always be cases (depending on viewport width and font size) where such messages will appear broken.
