### ISSUE TITLE
"Back" broken on Andorid Firefox

### ISSUE THREAD

**Issue by Abscissa** [CyberShadow/DFeed#57]
Haven't tried with other mobile browsers, but on Android Firefox:
1. Click on a link to go to a group (such as "Announce", "Learn", or "General").
2. Click on a link to go to a thread.
3. Click any "Reply" link.
4. Press "Back" to go back to the thread.
5. Press "Back" again.

Expected: Go back (to list of threads in group).

Actual: Current page (the thread) simply reloads.

**Comment by d-random-contributor** [comment]
Another scenario (works on desktop): click on the latest post link when that post is not on the last thread page, it will lead to `/thread/page...`, which will redirect to `/post/...`. If you press back, you'll go to `/thread/page...`, which will redirect to `/post/...` again.

**Comment by CyberShadow** [comment]
> Haven't tried with other mobile browsers, but on Android Firefox:

This is a bug in the web browser. Its `history.replaceState` is not working correctly. The problem does not occur with Chrome. Please report this to Mozilla.

> Another scenario (works on desktop):

I cannot reproduce this. Please provide steps to reproduce from a fresh Firefox profile (i.e. no extensions or cookies), preferably on a D group with low activity.

**Comment by Abscissa** [comment]
On March 18, 2016 10:15:09 AM EDT, Vladimir Panteleev <notifications@github.com> wrote:
>> Haven't tried with other mobile browsers, but on Android Firefox:
>
>This is a bug in the web browser. Its `history.replaceState` is not
>working correctly. The problem does not occur with Chrome. Please
>report this to Mozilla.
>
>> Another scenario (works on desktop):
>
>I cannot reproduce this. Please provide steps to reproduce from a fresh
>Firefox profile (i.e. no extensions or cookies), preferably on a D
>group with low activity.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CyberShadow/DFeed/issues/57#issuecomment-198378536

Browsers always have bugs, especially in their JS. I'm not sure I see the point of messing with the browser's history in script when regular back/forward is and has always been fully stable on all browsers for two decades. It's only going to invite problems like this.

**Comment by CyberShadow** [comment]
The use of the `history.replaceState` API, a standard feature of HTML5, is absolutely required to solve an annoyance that people have been complaining about until it was fixed. This annoyance was a direct result of forum.dlang.org being a newsgroup client and supporting multiple view modes, which is what motivated its creation in the first place. Reverting this behavior in order to work around a bug in a browser with a 0.81% market share for mobile devices alone is completely absurd (and I say this in spite of Firefox being my main browser on PC and Android), and frankly I don't see why I should waste any time on this issue at all.

If you can't even be bothered to take this to the Firefox bugtracker, you can probably disable JS completely on forum.dlang.org with NoScript or an equivalent extension.

**Comment by Abscissa** [comment]
On March 18, 2016 2:46:45 PM EDT, Vladimir Panteleev <notifications@github.com> wrote:
>The use of the `history.replaceState` API, a standard feature of HTML5,
>is absolutely required to solve an annoyance that people have been
>complaining about until it was fixed. This annoyance was a direct
>result of forum.dlang.org being a newsgroup client and supporting
>multiple view modes, which is what motivated its creation in the first
>place. Reverting this behavior in order to work around a bug in a
>browser with a 0.81% market share for mobile devices alone is
>completely absurd (and I say this in spite of Firefox being my main
>browser on PC and Android), and frankly I don't see why I should waste
>any time on this issue at all.
>
>If you can't even be bothered to take this to the Firefox bugtracker,
>you can probably disable JS completely on forum.dlang.org with NoScript
>or an equivalent extension.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CyberShadow/DFeed/issues/57#issuecomment-198491283

Whoa, nobody's demanding anything and nobody's refusing to report issues to mozilla, ok? I didn't even know it was a FF issue until you just told me. Just offered a thought on working around it. If there's a problem with that approach, can just correct me, no need for defensiveness.

Although I admit I'm not sure I'd be able to provide Mozilla with a much better report than "Something's apparently wrong with history.replaceState, not sure what exactly."

I am curious what annoyance it is you're referring to (that history.replaceState was needed to fix). I must've missed that. Happen to have a link handy?

**Comment by CyberShadow** [comment]
> Whoa, nobody's demanding anything and nobody's refusing to report issues to mozilla, ok? I didn't even know it was a FF issue until you just told me.

I did say in my first reply:

> This is a bug in the web browser. [...] Please report this to Mozilla.

Since you didn't reply to that part, I assumed that you weren't interested. Sorry if I was mistaken.

> Although I admit I'm not sure I'd be able to provide Mozilla with a much better report than "Something's apparently wrong with history.replaceState, not sure what exactly."

You could provide the same steps-to-reproduce you've provided here.

It is likely that someone has already reported this, though.

> I am curious what annoyance it is you're referring to (that history.replaceState was needed to fix). I must've missed that. Happen to have a link handy?

Essentially we need to correct a long URL, such as:

http://forum.dlang.org/thread/gmykvnuytmvypzxzhtfb@forum.dlang.org#post-iuaezaamjafnzerwpumk:40forum.dlang.org

into a canonical (short) one, such as:

http://forum.dlang.org/post/iuaezaamjafnzerwpumk@forum.dlang.org

The long URL (containing a #fragment) is needed to scroll to the correct post from a thread. The alternative would be to scroll using JavaScript, which would result in a worse UX.

The short URL is the canonical one, and will work in all view modes. The long URL will only work correctly in the basic view mode. People would often copy and share the long URLs, which aside from being excessively long (a complaint point in itself) would not "work" for people using other view modes (because the part indicating the exact port being linked to is not in the part of the URL getting sent to the web server).

Therefore, after letting the browser scroll to the correct post, we change the URL in the address bar using `history.replaceState` to the canonical one.

**Comment by d-random-contributor** [comment]
My scenario is as follows: click on the first unread post on a partially read thread, it will take you to the post; after this click on another link (e.g. dfeed help page link); press back, it will take you back to the post (at this point you can see a duplicate entry in the history menu); press back, it won't go back. When you go back and forth again, the duplicate entry in the history gets duplicated again.

**Comment by CyberShadow** [comment]
Yeah, I believe so.

**Comment by kskarthik** [comment]
I reproduced the steps above. Seems to work now. This issue Can be closed IMO
